<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\spectragrab.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <SplashScreen Include="Assets\spectrasgrab.png" />
    <Resource Include="Assets\spectragrab.ico" />
    <Resource Include="Assets\spectragrab-icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>

</Project>
